# Generated by Django 3.1.7 on 2021-03-05 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('short_description', models.TextField(max_length=256)),
                ('content', models.TextField()),
                ('image', models.URLField()),
                ('slug', models.SlugField(unique_for_date=True)),
            ],
        ),
    ]
