# Generated by Django 3.1.7 on 2021-03-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='linked_post',
        ),
    ]
